### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by pwallrich** [auxiliary/rpage#19]
Didn't work properly in chrome, with many pages.

edited the function calculateWidth. Now it's working correctly.
 `this.calculateWidth = function()
            {
                var width = 0;
                for (var i = 0; i < $container.find("li").length; i++)
                {
                    if(!($container.find("li").eq(i).css('display') == 'none'))
                    {
                        width += $container.find("li").eq(i).children("a").eq(0).outerWidth();
                        width += $container.find("li").eq(i).children("span").eq(0).outerWidth();
                    }
                }
                return width;
            }`

**Comment by auxiliary** [comment]
Yikes, two years ago. Thanks. Applied change in commit 8380a20b5849274f60957c3b211910e67d35ad34
