### ISSUE TITLE
jQuery.noConflict()

### ISSUE THREAD

**Issue by janogarcia** [auxiliary/rpage#6]
The plugin doesn't account for jQuery no-conflict configuration, and thus failing when trying to access the $ alias when jQuery is running in no-conflict mode.

The plugin code should be wrapped by `(function ($) { ... }(jQuery));`, `;(function ($, window, undefined) { ... })(jQuery, this);`, or any other variant.
http://learn.jquery.com/plugins/basic-plugin-creation/#protecting-the-alias-and-adding-scope

**Comment by auxiliary** [comment]
It's been a while since I haven't updated the repo. Done. Thank you.

**Comment by janogarcia** [comment]
No problem. Thanks for the udpate!
